apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::024411745340:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build  \n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::024411745340:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WG580O5LYY0B\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-22T19:39:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3967"
  uid: 226a5db4-efae-4854-b89a-0f427a976670
